function [fitresult, gof] = createFit(data_x, data_y)
%CREATEFIT(DATA_X,DATA_Y)
%  Create a fit.
%
%  Data for 'polynomial deg 8' fit:
%      X Input : data_x
%      Y Output: data_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Apr-2015 01:10:29


%% Fit: 'polynomial deg 8'.
[xData, yData] = prepareCurveData( data_x, data_y );

% Set up fittype and options.
ft = fittype( 'poly8' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'polynomial deg 8' );
h = plot( fitresult, xData, yData );
legend( h, 'data_y vs. data_x', 'polynomial deg 8', 'Location', 'NorthEast' );
% Label axes
xlabel data_x
ylabel data_y
grid on


