CC		= gcc
CFLAGS		= -g -Wall -pedantic
LDFLAGS		= -g

# Targets
PROGS =	crashing_prog infinite_loop interrupt_print sigaction_print sigproc_print alarm

all:	$(PROGS)

# Standard clean
clean:
	rm -f *.o $(PROGS)

